version: "2"
services:
#  relay:
#    build: .
#    ports:
#      - "8080:8080"
##      - "1883:1883"
#    depends_on:
#      - mosquitto
#      - kafka
#    environment:
##      SP_MQTT_HOST: localhost
##      SP_MQTT_PORT: 1883
##      SP_KAFKA_HOST: localhost
##      SP_KAFKA_PORT: 9094
#      SP_USE_EMBEDDED_BROKER: "false"

  mosquitto:
    image: eclipse-mosquitto:1.5.4
    ports:
      - "1883:1883"
    networks:
      relaynet:

  kafka:
    image: fogsyio/kafka:2.2.0
    hostname: kafka
    ports:
      - "9094:9094"
      - "9095:9095"
    depends_on:
      - zookeeper
    environment:
      # see: https://github.com/confluentinc/schema-registry/issues/648
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9094,EXTERNAL://141.21.12.73:9095 #(local, i.e. Single-Node with IDE + Docker)
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://:9094,EXTERNAL://:9095
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 5000012
      KAFKA_FETCH_MESSAGE_MAX_BYTES: 5000012
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      relaynet:

  zookeeper:
    image: fogsyio/zookeeper:3.4.13
    ports:
      - "2181:2181"
    networks:
      relaynet:

networks:
    relaynet:
      driver: bridge